        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 29 22:08:42 2016
        MODULE ELAPSED_TIME__genmod
          INTERFACE 
            FUNCTION ELAPSED_TIME
              REAL(KIND=8) :: ELAPSED_TIME
            END FUNCTION ELAPSED_TIME
          END INTERFACE 
        END MODULE ELAPSED_TIME__genmod
