        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 29 22:08:41 2016
        MODULE COMPUTE_INITIAL_CONDITIONS__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_INITIAL_CONDITIONS(U0,D1,D2,D3)
              INTEGER(KIND=4) :: D3
              INTEGER(KIND=4) :: D2
              INTEGER(KIND=4) :: D1
              COMPLEX(KIND=8) :: U0(D1+1,D2,D3)
            END SUBROUTINE COMPUTE_INITIAL_CONDITIONS
          END INTERFACE 
        END MODULE COMPUTE_INITIAL_CONDITIONS__genmod
