        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 29 22:08:41 2016
        MODULE COMPUTE_INDEXMAP__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_INDEXMAP(TWIDDLE,D1,D2,D3)
              INTEGER(KIND=4) :: D3
              INTEGER(KIND=4) :: D2
              INTEGER(KIND=4) :: D1
              REAL(KIND=8) :: TWIDDLE(D1+1,D2,D3)
            END SUBROUTINE COMPUTE_INDEXMAP
          END INTERFACE 
        END MODULE COMPUTE_INDEXMAP__genmod
