        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 29 22:08:41 2016
        MODULE IPOW46__genmod
          INTERFACE 
            SUBROUTINE IPOW46(A,EXPONENT,RESULT)
              REAL(KIND=8) :: A
              INTEGER(KIND=4) :: EXPONENT
              REAL(KIND=8) :: RESULT
            END SUBROUTINE IPOW46
          END INTERFACE 
        END MODULE IPOW46__genmod
